### ISSUE TITLE
Can we config the folder where `CHANGELOG.md` lives in?

### ISSUE THREAD

**Issue by zhuoqun-chen** [callowayproject/generate-changelog#31]
Hi @coordt, thank you for making this amazing tool!

I have a use case though and hope that you can give me some hints:

is there a way I can put `CHANGELOG.md` into subdir, say, `projectRoot/<dir>/CHANGELOG.md`?

**Comment by coordt** [comment]
I'm looking into this today.

**Comment by coordt** [comment]
@zhuoqun-chen You should be able to add/modify the `variables:` configuration, like

```yaml
variables:
  changelog_filename: ./<dir>/CHANGELOG.md
```

Let me know if that doesn't work.

**Comment by zhuoqun-chen** [comment]
Still won't work. But I think I can use a shell script to move it into package after some automation steps. 

Here's the log, I kept the changelog config at `projectRoot`, and changelog file itself under `<projectRoot>/<dir>/CHANGELOG.md` with `./<dir>/CHANGELOG.md` as you suggested:


```shell
Traceback (most recent call last):
  File "/home/node/miniforge3/bin/bump-my-version", line 8, in <module>
    sys.exit(cli())
  File "/home/node/miniforge3/lib/python3.10/site-packages/rich_click/rich_command.py", line 367, in __call__
    return super().__call__(*args, **kwargs)
  File "/home/node/miniforge3/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/node/miniforge3/lib/python3.10/site-packages/rich_click/rich_command.py", line 152, in main
    rv = self.invoke(ctx)
  File "/home/node/miniforge3/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/node/miniforge3/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/node/miniforge3/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/node/miniforge3/lib/python3.10/site-packages/bumpversion/cli.py", line 309, in bump
    do_bump(version_part, new_version, config, found_config_file, dry_run)
  File "/home/node/miniforge3/lib/python3.10/site-packages/bumpversion/bump.py", line 104, in do_bump
    modify_files(configured_files, version, next_version, ctx, dry_run)
  File "/home/node/miniforge3/lib/python3.10/site-packages/bumpversion/files.py", line 269, in modify_files
    f.make_file_change(current_version, new_version, context, dry_run)
  File "/home/node/miniforge3/lib/python3.10/site-packages/bumpversion/files.py", line 187, in make_file_change
    raise FileNotFoundError(f"File not found: '{self.file_change.filename}'")  # pragma: no-coverage
FileNotFoundError: File not found: 'CHANGELOG.md'
```

**Comment by coordt** [comment]
@zhuoqun-chen Looking deeper. Thanks for the update.

**Comment by coordt** [comment]
@zhuoqun-chen OK, I created a test to ensure it works as expected.

Then I looked at your traceback and realized the issue was not with `generate-changelog` but with `bumpversion`.

If you are using my `bump-my-version` then change the configuration of the changelog path there so it makes updates correctly

**Comment by zhuoqun-chen** [comment]
@coordt Thx! yeah I indeed use `bump-my-version` together with `generate-changelog`. Now it makes sense and fixes the problem. Have a nice day! 😃
